<a href="https://colab.research.google.com/github/ngwalker93/ADS-507-Final-Team-Project/blob/main/ADS507_Final_FDA_Shortage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests
import zipfile
import io
import os
import json

url = "https://download.open.fda.gov/drug/ndc/drug-ndc-0001-of-0001.json.zip"

# Download the file
response = requests.get(url)
response.raise_for_status()

zip_bytes = io.BytesIO(response.content)

with zipfile.ZipFile(zip_bytes) as z:
    z.extractall("data")

json_path = "data/drug-ndc-0001-of-0001.json"

# Load JSON file first, then extract the results
with open(json_path, 'r') as f:
    data = json.load(f)

# The actual drug data is in the 'results' key
df = pd.DataFrame(data['results'])

df.head()

,product_ndc,generic_name,labeler_name,brand_name,active_ingredients,finished,packaging,listing_expiration_date,openfda,marketing_category,...,product_type,route,marketing_start_date,product_id,application_number,brand_name_base,pharm_class,dea_schedule,marketing_end_date,brand_name_suffix
0,75834-264,diclofenac sodium and misoprostol,"Nivagen Pharmaceuticals, Inc.",Diclofenac Sodium Misoprostol,"[{'name': 'DICLOFENAC SODIUM', 'strength': '50...",True,"[{'package_ndc': '75834-264-60', 'description'...",20271231,{'manufacturer_name': ['Nivagen Pharmaceutical...,ANDA,...,HUMAN PRESCRIPTION DRUG,[ORAL],20210715,75834-264_542fd9dd-a6d3-4432-9e7a-2ca5bce12956,ANDA205143,Diclofenac Sodium Misoprostol,"[Anti-Inflammatory Agents, Non-Steroidal [CS],...",NaN,NaN,NaN
1,75834-294,Erythromycin Ethylsuccinate,"Nivagen Pharmaceuticals, Inc.",Erythromycin Ethylsuccinate,"[{'name': 'ERYTHROMYCIN ETHYLSUCCINATE', 'stre...",True,"[{'package_ndc': '75834-294-01', 'description'...",20261231,{'manufacturer_name': ['Nivagen Pharmaceutical...,ANDA,...,HUMAN PRESCRIPTION DRUG,[ORAL],20230201,75834-294_7f06e8f4-15fb-4e18-b57e-457e7e20d331,ANDA216212,Erythromycin Ethylsuccinate,"[Decreased Sebaceous Gland Activity [PE], Macr...",NaN,NaN,NaN
2,75834-295,Erythromycin Ethylsuccinate,"Nivagen Pharmaceuticals, Inc.",Erythromycin Ethylsuccinate,"[{'name': 'ERYTHROMYCIN ETHYLSUCCINATE', 'stre...",True,"[{'package_ndc': '75834-295-01', 'description'...",20261231,{'manufacturer_name': ['Nivagen Pharmaceutical...,ANDA,...,HUMAN PRESCRIPTION DRUG,[ORAL],20230201,75834-295_7f06e8f4-15fb-4e18-b57e-457e7e20d331,ANDA216212,Erythromycin Ethylsuccinate,"[Decreased Sebaceous Gland Activity [PE], Macr...",NaN,NaN,NaN
3,75834-315,"thyroid, porcine","Nivagen Pharmaceuticals, Inc.",Niva Thyroid,"[{'name': 'THYROID', 'strength': '180 mg/1'}]",True,"[{'package_ndc': '75834-315-01', 'description'...",20261231,{'manufacturer_name': ['Nivagen Pharmaceutical...,UNAPPROVED DRUG OTHER,...,HUMAN PRESCRIPTION DRUG,[ORAL],20230724,75834-315_1cce3de8-0aa9-4f05-9104-a84b7d91dd68,NaN,Niva Thyroid,NaN,NaN,NaN,NaN
4,75834-333,lidocaine,"Nivagen Pharmaceuticals, Inc.",lidocaine,"[{'name': 'LIDOCAINE', 'strength': '50 mg/g'}]",True,"[{'package_ndc': '75834-333-30', 'description'...",20261231,{'manufacturer_name': ['Nivagen Pharmaceutical...,OTC MONOGRAPH DRUG,...,HUMAN OTC DRUG,[TOPICAL],20250105,75834-333_8ab252ef-f8ee-442b-bcf4-a44c57448cba,M015,lidocaine,"[Amide Local Anesthetic [EPC], Amides [CS], An...",NaN,NaN,NaN

In [2]:
# List all column names in the raw NDC dataset

df.columns.tolist()

['product_ndc',
 'generic_name',
 'labeler_name',
 'brand_name',
 'active_ingredients',
 'finished',
 'packaging',
 'listing_expiration_date',
 'openfda',
 'marketing_category',
 'dosage_form',
 'spl_id',
 'product_type',
 'route',
 'marketing_start_date',
 'product_id',
 'application_number',
 'brand_name_base',
 'pharm_class',
 'dea_schedule',
 'marketing_end_date',
 'brand_name_suffix']

In [3]:
# Column data types
df.dtypes

product_ndc                object
generic_name               object
labeler_name               object
brand_name                 object
active_ingredients         object
finished                     bool
packaging                  object
listing_expiration_date    object
openfda                    object
marketing_category         object
dosage_form                object
spl_id                     object
product_type               object
route                      object
marketing_start_date       object
product_id                 object
application_number         object
brand_name_base            object
pharm_class                object
dea_schedule               object
marketing_end_date         object
brand_name_suffix          object
dtype: object

In [6]:
# Check the 'marketing_start_date' and 'marketing_end_date' columns format
for c in ["marketing_start_date", "marketing_end_date"]:
    print("\n", c)
    print(df[c].dtype)
    print(df[c].head(10).tolist())
    print(df[c].astype("string").str.strip().value_counts(dropna=False).head(3))

 marketing_start_date
string
['2021-07-15', '2023-02-01', '2023-02-01', '2023-07-24', '2025-01-05', '2013-01-16', '2024-09-01', '2024-02-10', '2024-03-15', '2024-08-22']
marketing_start_date
1983-03-03    1763
1981-09-15    1291
2015-01-01     675
Name: count, dtype: Int64

 marketing_end_date
string
[<NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>]
marketing_end_date
<NA>          126523
2026-01-31       231
2026-02-28       223
Name: count, dtype: Int64

In [7]:
# Standardize raw FDA field names into ISO-8601 formate to facilitate downstream processing. 
# Ensures dates fields are loaded as native DATE in MySQL 
date_cols = ['listing_expiration_date', 'marketing_start_date', 'marketing_end_date']

def yyyymmdd_to_iso(series: pd.Series) -> pd.Series:
    s = series.astype("string").str.strip()

    # normalize missing/placeholder values to NaT
    s = s.replace({"": pd.NA, "nan": pd.NA, "NaN": pd.NA,
        "None": pd.NA, "null": pd.NA, "NULL": pd.NA,
        "0": pd.NA, "00000000": pd.NA})
    
    # parse YYYYMMDD to date 
    dt = pd.to_datetime(s, format="%Y%m%d", errors="coerce")

    # Return ISO string for MySQL/CSV: "YYYY-MM-DD" (or <NA> for missing)
    return dt.dt.strftime("%Y-%m-%d").astype("string")

for col in date_cols:
    df[col] = yyyymmdd_to_iso(df[col])

# Verify date conversion
for c in date_cols:
    print("\n", c)
    print(df[c].dtype)
    print(df[c].head(10).tolist())
    print(df[c].value_counts(dropna=False).head(3))

 listing_expiration_date
string
[<NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>]
listing_expiration_date
<NA>    131118
Name: count, dtype: Int64

 marketing_start_date
string
[<NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>]
marketing_start_date
<NA>    131118
Name: count, dtype: Int64

 marketing_end_date
string
[<NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>]
marketing_end_date
<NA>    131118
Name: count, dtype: Int64

## Inspect Nested NDC Fields

In [8]:
# Packaging Field inspection
df.loc[df["packaging"].notna(), "packaging"].iloc[0]

[{'package_ndc': '75834-264-60',
  'description': '60 TABLET, DELAYED RELEASE in 1 BOTTLE (75834-264-60)',
  'marketing_start_date': '20210715',
  'sample': False},
 {'package_ndc': '75834-264-90',
  'description': '90 TABLET, DELAYED RELEASE in 1 BOTTLE (75834-264-90)',
  'marketing_start_date': '20210715',
  'sample': False}]

packaging is a list of dicts including package_ndc, description, marketing_start_date, and sample. THis is a one-to-many relationship with the main drug table. This column can be separated out into its own table. 

Foreign key: product_ndc

In [10]:
# Check dictionary keys used in 'packaging' field
keys = set()
for lst in df.loc[df["packaging"].notna(), "packaging"].head(500):
    for d in (lst if isinstance(lst, list) else []):
        if isinstance(d, dict):
            keys.update(d.keys())
sorted(keys)

['description',
 'marketing_end_date',
 'marketing_start_date',
 'package_ndc',
 'sample']

In [11]:
# Create a one-to-many packaging table linked by product_ndc

packaging_rows = []

for _, row in df[["product_ndc", "packaging"]].dropna().iterrows():
    for pkg in row["packaging"]:
        pkg_row = {
            "product_ndc": row["product_ndc"],
            "package_ndc": pkg.get("package_ndc"),
            "description": pkg.get("description"),
            "marketing_start_date": pkg.get("marketing_start_date"),
            "marketing_end_date": pkg.get("marketing_end_date"),
            "sample": pkg.get("sample"),
        }
        packaging_rows.append(pkg_row)

# Build packaging DataFrame
ndc_packaging = pd.DataFrame(packaging_rows)

# normalize packaging-level dates to YYYY-MM-DD strings for MySQL DATE
for col in ["marketing_start_date", "marketing_end_date"]:
    if col in ndc_packaging.columns:
        ndc_packaging[col] = pd.to_datetime(
            ndc_packaging[col].astype("string").str.strip().str.replace(r"\.0$", "", regex=True),
            format="%Y%m%d",
            errors="coerce"
        ).dt.strftime("%Y-%m-%d").astype("string")

# ensure boolean "sample' column is boolean (and MySQL-friendly later)
if "sample" in ndc_packaging.columns:
    ndc_packaging["sample"] = (
    ndc_packaging["sample"]
        .fillna(False)
        .infer_objects(copy=False)
        .astype(bool))

ndc_packaging.head()

/var/folders/4d/9t08wrpn3gvcfr0wtwc31yx80000gn/T/ipykernel_5938/2918935697.py:33: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(False)

,product_ndc,package_ndc,description,marketing_start_date,marketing_end_date,sample
0,75834-264,75834-264-60,"60 TABLET, DELAYED RELEASE in 1 BOTTLE (75834-...",2021-07-15,<NA>,False
1,75834-264,75834-264-90,"90 TABLET, DELAYED RELEASE in 1 BOTTLE (75834-...",2021-07-15,<NA>,False
2,75834-294,75834-294-01,100 mL in 1 BOTTLE (75834-294-01),2023-02-01,<NA>,False
3,75834-295,75834-295-01,100 mL in 1 BOTTLE (75834-295-01),2023-02-01,<NA>,False
4,75834-315,75834-315-01,100 TABLET in 1 BOTTLE (75834-315-01),2023-07-24,<NA>,False

In [12]:
# Active Ingredients Field inspection
df.loc[df["active_ingredients"].notna(), "active_ingredients"].iloc[0]

[{'name': 'DICLOFENAC SODIUM', 'strength': '50 mg/1'},
 {'name': 'MISOPROSTOL', 'strength': '200 ug/1'}]

In [13]:
keys = set()
for lst in df.loc[df["active_ingredients"].notna(), "active_ingredients"].head(500):
    for d in (lst if isinstance(lst, list) else []):
        if isinstance(d, dict):
            keys.update(d.keys())
sorted(keys)

['name', 'strength']

Active ingredients is also a list of dictionaries including name and strenght. This can also be separated out into its own table. 

Foreign key: product_ndc

In [14]:
active_rows = []

for _, row in df[["product_ndc", "active_ingredients"]].dropna().iterrows():
    for ing in row["active_ingredients"]:
        active_rows.append({
            "product_ndc": row["product_ndc"],
            "name": ing.get("name"),
            "strength": ing.get("strength"),})

# Build active ingredients DataFrame
ndc_active_ingredients = pd.DataFrame(active_rows)
ndc_active_ingredients.head()

  product_ndc                         name    strength
0   75834-264            DICLOFENAC SODIUM     50 mg/1
1   75834-264                  MISOPROSTOL    200 ug/1
2   75834-294  ERYTHROMYCIN ETHYLSUCCINATE  400 mg/5mL
3   75834-295  ERYTHROMYCIN ETHYLSUCCINATE  200 mg/5mL
4   75834-315                      THYROID    180 mg/1

In [15]:
# OpenFDA Field inspection
df.loc[df["openfda"].notna(), "openfda"].iloc[0]

{'manufacturer_name': ['Nivagen Pharmaceuticals, Inc.'],
 'rxcui': ['857706', '1359105'],
 'spl_set_id': ['2acf46ac-8ba8-444d-b421-19d5ad49644c'],
 'is_original_packager': [True],
 'upc': ['0375834264608', '0375834265605'],
 'nui': ['N0000175785', 'M0017811'],
 'pharm_class_epc': ['Prostaglandin E1 Analog [EPC]'],
 'pharm_class_cs': ['Prostaglandins E, Synthetic [CS]'],
 'unii': ['0E43V0BB57', 'QTG126297Q']}

OpenFDA is a dictionary of string values. It can be separated into it's own reference table. It includes metadata about the product. Useful for join NDC → openfda → RxCUI / UNII lookups, manufacturer analyse, and matching shortages to standardized identifiers. 

Foreign key: product_ndc

In [16]:
# Inspect the keys 
keys = set()
for d in df.loc[df["openfda"].notna(), "openfda"].head(1000):
    if isinstance(d, dict):
        keys.update(d.keys())
sorted(keys)

['is_original_packager',
 'manufacturer_name',
 'nui',
 'pharm_class_cs',
 'pharm_class_epc',
 'pharm_class_moa',
 'pharm_class_pe',
 'rxcui',
 'spl_set_id',
 'unii',
 'upc']

In [17]:
# Transform openfda field into a separate one-to-one table
openfda_rows = []

for _, row in df[["product_ndc", "openfda"]].dropna().iterrows():
    d = row["openfda"]
    if not isinstance(d, dict):
        continue

    flat = {"product_ndc": row["product_ndc"]}

    for k, v in d.items():
        # most values are lists; keep first element
        if isinstance(v, list):
            flat[k] = v[0] if len(v) > 0 else None
        else:
            flat[k] = v

    openfda_rows.append(flat)

ndc_openfda = pd.DataFrame(openfda_rows)

# clean strings
for c in ndc_openfda.columns:
    if c != "product_ndc":
        ndc_openfda[c] = ndc_openfda[c].astype("string").str.strip()

ndc_openfda.head()

,product_ndc,manufacturer_name,rxcui,spl_set_id,is_original_packager,upc,nui,pharm_class_epc,pharm_class_cs,unii,pharm_class_pe,pharm_class_moa
0,75834-264,"Nivagen Pharmaceuticals, Inc.",857706,2acf46ac-8ba8-444d-b421-19d5ad49644c,True,0375834264608,N0000175785,Prostaglandin E1 Analog [EPC],"Prostaglandins E, Synthetic [CS]",0E43V0BB57,<NA>,<NA>
1,75834-294,"Nivagen Pharmaceuticals, Inc.",686400,46f74c4f-10fc-44cf-aec4-d113f49149bc,True,0375834295015,<NA>,<NA>,<NA>,1014KSJ86F,<NA>,<NA>
2,75834-295,"Nivagen Pharmaceuticals, Inc.",686400,46f74c4f-10fc-44cf-aec4-d113f49149bc,True,0375834295015,<NA>,<NA>,<NA>,1014KSJ86F,<NA>,<NA>
3,75834-315,"Nivagen Pharmaceuticals, Inc.",198278,eae7789a-d85d-4b04-a680-e688a371ebee,True,0375834316017,<NA>,<NA>,<NA>,6RV024OAUQ,<NA>,<NA>
4,75834-333,"Nivagen Pharmaceuticals, Inc.",1366789,32964ec3-1880-477b-9f71-2222c39106aa,True,0375834333304,N0000175682,Amide Local Anesthetic [EPC],Amides [CS],98PI200987,Local Anesthesia [PE],<NA>

In [18]:
# Create a clean, flat core NDC products table to serve as the primary
# reference table for joining with FDA drug shortage data.
# This table keeps only one-to-one product attributes (no nested fields).

ndc_core_cols = [
    "product_ndc",              # Primary identifier / join key
    "brand_name",
    "generic_name",
    "labeler_name",
    "product_type",
    "marketing_category",
    "dosage_form",
    "route",
    "finished",
    "listing_expiration_date",
    "marketing_start_date",
    "marketing_end_date",
    "application_number",
    "pharm_class",
    "dea_schedule"
]

ndc_products = df[ndc_core_cols].copy()

ndc_products.head()

,product_ndc,brand_name,generic_name,labeler_name,product_type,marketing_category,dosage_form,route,finished,listing_expiration_date,marketing_start_date,marketing_end_date,application_number,pharm_class,dea_schedule
0,75834-264,Diclofenac Sodium Misoprostol,diclofenac sodium and misoprostol,"Nivagen Pharmaceuticals, Inc.",HUMAN PRESCRIPTION DRUG,ANDA,"TABLET, DELAYED RELEASE",[ORAL],True,<NA>,<NA>,<NA>,ANDA205143,"[Anti-Inflammatory Agents, Non-Steroidal [CS],...",NaN
1,75834-294,Erythromycin Ethylsuccinate,Erythromycin Ethylsuccinate,"Nivagen Pharmaceuticals, Inc.",HUMAN PRESCRIPTION DRUG,ANDA,SUSPENSION,[ORAL],True,<NA>,<NA>,<NA>,ANDA216212,"[Decreased Sebaceous Gland Activity [PE], Macr...",NaN
2,75834-295,Erythromycin Ethylsuccinate,Erythromycin Ethylsuccinate,"Nivagen Pharmaceuticals, Inc.",HUMAN PRESCRIPTION DRUG,ANDA,SUSPENSION,[ORAL],True,<NA>,<NA>,<NA>,ANDA216212,"[Decreased Sebaceous Gland Activity [PE], Macr...",NaN
3,75834-315,Niva Thyroid,"thyroid, porcine","Nivagen Pharmaceuticals, Inc.",HUMAN PRESCRIPTION DRUG,UNAPPROVED DRUG OTHER,TABLET,[ORAL],True,<NA>,<NA>,<NA>,NaN,NaN,NaN
4,75834-333,lidocaine,lidocaine,"Nivagen Pharmaceuticals, Inc.",HUMAN OTC DRUG,OTC MONOGRAPH DRUG,CREAM,[TOPICAL],True,<NA>,<NA>,<NA>,M015,"[Amide Local Anesthetic [EPC], Amides [CS], An...",NaN

Note: Missing values appear as either NaN or <NA> depending on pandas dtype inference. Since both serialize to SQL NULL during loading, no correction is required for MySQL.

In [19]:
# Confirm how many rows and columns are in the core NDC table

ndc_products.shape

(131118, 15)

In [20]:
# Show the proportion of missing values for each column in the core NDC table

ndc_products.isna().mean().sort_values(ascending=False)

listing_expiration_date    1.000000
marketing_start_date       1.000000
marketing_end_date         1.000000
dea_schedule               0.952272
pharm_class                0.456223
application_number         0.280236
route                      0.173378
brand_name                 0.160092
generic_name               0.000023
product_ndc                0.000000
labeler_name               0.000000
product_type               0.000000
marketing_category         0.000000
dosage_form                0.000000
finished                   0.000000
dtype: float64

In [21]:
# Confirm multiple packaging records exist per product_ndc

ndc_packaging.groupby("product_ndc").size().sort_values(ascending=False).head()

product_ndc
59579-002    63
84165-016    59
84165-102    58
84165-006    55
84165-002    54
dtype: int64

One product can have many packages. Many rows per product exist.

In [22]:
# rename ingredient name column for clarity
ndc_active_ingredients = ndc_active_ingredients.rename(columns={"name": "ingredient_name"})
# Confirm multiple active ingredient records exist per product_ndc
ndc_active_ingredients.duplicated(subset=["product_ndc", "ingredient_name"]).sum()

np.int64(2625)

In [23]:
# Confirm multiple active ingredient records exist per product_ndc
ndc_active_ingredients.groupby("product_ndc").size().sort_values(ascending=False).head()

product_ndc
62713-958    102
62713-959    102
62713-968    102
62713-969    102
62713-980    101
dtype: int64

Active ingredients were modeled as a one-to-many child table. Cardinality checks confirmed multiple ingredient records per product, and duplicate product–ingredient combinations were validated to ensure relational integrity

In [24]:
# Confirm one-to-one relationship in openfda table
ndc_openfda.groupby("product_ndc").size().value_counts()

1     126967
2       1595
3        158
4         55
6         11
5          5
9          3
8          2
10         2
7          2
13         1
17         1
22         1
36         1
11         1
Name: count, dtype: int64

openfda is NOT strictly one-to-one with product_ndc in the data.
There are multiple identifiers per product. 

Collapse to one row per product

In [54]:
# Collapse openfda table into one row per product_ndc by keeping the first non-null value for each column
ndc_openfda_collapsed = (
    ndc_openfda
      .groupby("product_ndc", as_index=False)
      .agg({
          "manufacturer_name": lambda x: "|".join(sorted(set(x.dropna()))),
          "rxcui": lambda x: "|".join(sorted(set(x.dropna()))),
          "spl_set_id": lambda x: "|".join(sorted(set(x.dropna()))),
          "upc": lambda x: "|".join(sorted(set(x.dropna()))),
          "unii": lambda x: "|".join(sorted(set(x.dropna()))),
      })
)
ndc_openfda_collapsed.head(20)

,product_ndc,manufacturer_name,rxcui,spl_set_id,upc,unii
0,0002-0013,,,,,
1,0002-0095,,,,,
2,0002-0096,,,,,
3,0002-0113,,,,,
4,0002-0119,,,,,
5,0002-0121,,,,,
6,0002-0124,,,,,
7,0002-0137,,,,,
8,0002-0152,Eli Lilly and Company,2601743,487cd7e7-434c-4925-99fa-aa80b1cc776b,0300022002045,OYN3CCI6QE
9,0002-0213,Eli Lilly and Company,311034,b519bd83-038c-4ec5-a231-a51ec5cc291f,0300028215012,1Y17CTI5SR
10,0002-0243,Eli Lilly and Company,2601743,487cd7e7-434c-4925-99fa-aa80b1cc776b,0300022002045,OYN3CCI6QE
11,0002-0485,,,,,
12,0002-0535,,,,,
13,0002-0770,,,,,
14,0002-0800,Eli Lilly and Company,242120,c8ecbd7a-0e22-4fc7-a503-faa58c1b6f3f,,059QF0KO0R
15,0002-0872,,,,,
16,0002-1076,,,,,
17,0002-1099,,,,,
18,0002-1152,Eli Lilly and Company,2601743,d2d7da5d-ad07-4228-955f-cf7e355c8cc0,0300023002013,OYN3CCI6QE
19,0002-1200,Eli Lilly and Company,,bb5a5043-0f51-11df-8a39-0800200c9a66,,6W15Z5R0RU

In [26]:
# Confirm one-to-one relationship in collapsed openfda table
ndc_openfda_collapsed.groupby("product_ndc").size().value_counts()

1    128805
Name: count, dtype: int64

OpenFDA is stored in a curated, one-row-per-product table to support reliable joins

Although the NDC dataset contains an openfda enrichment object, its identifiers are sparse and primarily intended for cross-endpoint linkage, which is outside the scope of this project’s shortage-focused analysis. Will Keep it as a filtered enrichment table that includes only rows where at least one openfda field exists. It is not used in joins for core analysis and analytical logic is not built around it.

In [24]:
# Save reduced tables locally for reuse in later steps

ndc_products.to_csv("data/ndc_products.csv", index=False)
ndc_packaging.to_csv("data/ndc_packaging.csv", index=False)
ndc_active_ingredients.to_csv("data/ndc_active_ingredients.csv", index=False)
ndc_openfda_collapsed.to_csv("data/ndc_openfda_collapsed.csv", index=False, na_rep="")

In [27]:
# URL for the openFDA drug shortages dataset
shortages_url = "https://download.open.fda.gov/drug/shortages/drug-shortages-0001-of-0001.json.zip"

# Download the file
response = requests.get(shortages_url)
response.raise_for_status()

zip_bytes = io.BytesIO(response.content)

with zipfile.ZipFile(zip_bytes) as z:
    z.extractall("data")

shortages_json_path = "data/drug-shortages-0001-of-0001.json"

# Load JSON and extract the actual records from 'results'
with open(shortages_json_path, "r") as f:
    shortages_data = json.load(f)

shortage_df = pd.DataFrame(shortages_data["results"])

shortage_df.head()

,discontinued_date,update_type,initial_posting_date,package_ndc,generic_name,contact_info,related_info,openfda,update_date,therapeutic_category,presentation,company_name,status,availability,dosage_form,related_info_link,shortage_reason,change_date,resolved_note
0,10/09/2025,New,10/09/2025,0781-2868-10,Omeprazole Delayed Release Capsule,800-525-8747,Discontinuation of the manufacture of the drug,"{'application_number': ['ANDA075757'], 'brand_...",10/09/2025,[Gastroenterology],"Omeprazole, Delayed Release Capsule, 20 mg (ND...",Sandoz Inc.,To Be Discontinued,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Reverified,03/10/2023,72888-153-05,Clonazepam Tablet,sales@advagenpharma.com,Marketed by Advagen Pharma Ltd.,"{'application_number': ['ANDA075468'], 'brand_...",01/05/2026,"[Neurology, Pediatric, Psychiatry]","Clonazepam, Tablet, 1 mg (NDC 72888-153-05)",Rubicon Research Private Limited,Current,Available,Tablet,NaN,NaN,NaN,NaN
2,11/03/2025,New,11/03/2025,0003-3641-11,Atazanavir Sulfate; Cobicistat Tablet,800-332-2056,The global Cease Manufacture date for EVOTAZ® ...,"{'application_number': ['NDA206353'], 'brand_n...",11/03/2025,[Antiviral],"Evotaz, Tablet, 300 mg; 150 mg (NDC 0003-3641-11)",Bristol Myers Squibb Co.,To Be Discontinued,NaN,Tablet,NaN,NaN,NaN,NaN
3,NaN,Reverified,04/28/2023,0990-6139-03,Sterile Water Irrigant,1-866-829-9025 or ProductAvailability@icumed.com,Allocated to Contracted Customers Only. Estima...,"{'application_number': ['NDA017513'], 'brand_n...",01/23/2026,"[Gastroenterology, Other, Pediatric]","Sterile Water In Plastic Container, Irrigant, ...",Otsuka ICU Medical LLC,Current,Limited Availability,Irrigant,https://www.fda.gov/media/182619/download?atta...,Other,NaN,NaN
4,NaN,Revised,05/03/2022,17478-050-05,Sufentanil Citrate Injection,800-631-2174,Not currently manufactured,NaN,01/22/2026,"[Analgesia/Addiction, Pediatric]","Sufentanil Citrate, Injection, 50 mcg/1 mL (ND...","Hikma Pharmaceuticals USA, Inc.",Current,Unavailable,Injection,NaN,Other,NaN,NaN

In [28]:
# Check shape

shortage_df.shape

(1838, 19)

In [29]:
# Check the 'discontinued_date', 'initial_posting_date', and 'update_date' columns format
for c in ["discontinued_date", "initial_posting_date", "update_date"]:
    print("\n", c)
    print(shortage_df[c].dtype)
    print(shortage_df[c].head(10).tolist())
    print(shortage_df[c].astype("string").str.strip().value_counts(dropna=False).head(3))

 discontinued_date
object
['10/09/2025', nan, '11/03/2025', nan, nan, '11/03/2025', nan, nan, nan, nan]
discontinued_date
<NA>          1313
06/13/2025      35
07/10/2025      22
Name: count, dtype: Int64

 initial_posting_date
object
['10/09/2025', '03/10/2023', '11/03/2025', '04/28/2023', '05/03/2022', '11/03/2025', '01/06/2023', '03/03/2025', '07/14/2023', '02/15/2023']
initial_posting_date
07/14/2023    99
10/12/2022    72
02/20/2018    70
Name: count, dtype: Int64

 update_date
object
['10/09/2025', '01/05/2026', '11/03/2025', '01/23/2026', '01/22/2026', '11/03/2025', '08/28/2025', '09/17/2025', '01/21/2026', '01/23/2026']
update_date
01/23/2026    223
01/06/2026    162
01/15/2026    126
Name: count, dtype: Int64

In [30]:
# Convert date columns to ISO-8601 format for MySQL DATE compatibility
date_cols = ['discontinued_date', 'initial_posting_date', 'update_date']
for col in date_cols:
    dt = pd.to_datetime(shortage_df[col], format="%m/%d/%Y", errors="coerce")
    shortage_df[col] = dt.dt.strftime("%Y-%m-%d").astype("string")
# Verify date conversion
for c in date_cols:
    print("\n", c)
    print(shortage_df[c].dtype)
    print(shortage_df[c].head(10).tolist())
    print(shortage_df[c].value_counts(dropna=False).head(3))

 discontinued_date
string
['2025-10-09', <NA>, '2025-11-03', <NA>, <NA>, '2025-11-03', <NA>, <NA>, <NA>, <NA>]
discontinued_date
<NA>          1313
2025-06-13      35
2025-07-10      22
Name: count, dtype: Int64

 initial_posting_date
string
['2025-10-09', '2023-03-10', '2025-11-03', '2023-04-28', '2022-05-03', '2025-11-03', '2023-01-06', '2025-03-03', '2023-07-14', '2023-02-15']
initial_posting_date
2023-07-14    99
2022-10-12    72
2018-02-20    70
Name: count, dtype: Int64

 update_date
string
['2025-10-09', '2026-01-05', '2025-11-03', '2026-01-23', '2026-01-22', '2025-11-03', '2025-08-28', '2025-09-17', '2026-01-21', '2026-01-23']
update_date
2026-01-23    223
2026-01-06    162
2026-01-15    126
Name: count, dtype: Int64

In [31]:
# List columns

shortage_df.columns.tolist()

['discontinued_date',
 'update_type',
 'initial_posting_date',
 'package_ndc',
 'generic_name',
 'contact_info',
 'related_info',
 'openfda',
 'update_date',
 'therapeutic_category',
 'presentation',
 'company_name',
 'status',
 'availability',
 'dosage_form',
 'related_info_link',
 'shortage_reason',
 'change_date',
 'resolved_note']

In [32]:
# Create core drug shortage table for analysis and joining to NDC packaging

shortage_core_cols = [
    "package_ndc",
    "generic_name",
    "company_name",
    "status",
    "availability",
    "shortage_reason",
    "update_type",
    "initial_posting_date",
    "update_date",
    "discontinued_date",
    "change_date",
    "resolved_note",
    "therapeutic_category",
    "dosage_form",
    "presentation"
]

drug_shortages = shortage_df[shortage_core_cols].copy()

drug_shortages.head()

,package_ndc,generic_name,company_name,status,availability,shortage_reason,update_type,initial_posting_date,update_date,discontinued_date,change_date,resolved_note,therapeutic_category,dosage_form,presentation
0,0781-2868-10,Omeprazole Delayed Release Capsule,Sandoz Inc.,To Be Discontinued,NaN,NaN,New,2025-10-09,2025-10-09,2025-10-09,NaN,NaN,[Gastroenterology],NaN,"Omeprazole, Delayed Release Capsule, 20 mg (ND..."
1,72888-153-05,Clonazepam Tablet,Rubicon Research Private Limited,Current,Available,NaN,Reverified,2023-03-10,2026-01-05,<NA>,NaN,NaN,"[Neurology, Pediatric, Psychiatry]",Tablet,"Clonazepam, Tablet, 1 mg (NDC 72888-153-05)"
2,0003-3641-11,Atazanavir Sulfate; Cobicistat Tablet,Bristol Myers Squibb Co.,To Be Discontinued,NaN,NaN,New,2025-11-03,2025-11-03,2025-11-03,NaN,NaN,[Antiviral],Tablet,"Evotaz, Tablet, 300 mg; 150 mg (NDC 0003-3641-11)"
3,0990-6139-03,Sterile Water Irrigant,Otsuka ICU Medical LLC,Current,Limited Availability,Other,Reverified,2023-04-28,2026-01-23,<NA>,NaN,NaN,"[Gastroenterology, Other, Pediatric]",Irrigant,"Sterile Water In Plastic Container, Irrigant, ..."
4,17478-050-05,Sufentanil Citrate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,Unavailable,Other,Revised,2022-05-03,2026-01-22,<NA>,NaN,NaN,"[Analgesia/Addiction, Pediatric]",Injection,"Sufentanil Citrate, Injection, 50 mcg/1 mL (ND..."

In [34]:
# Preview the contact_info field to understand its structure before normalization

shortage_df["contact_info"].head(20)

0                                         800-525-8747
1                              sales@advagenpharma.com
2                                         800-332-2056
3     1-866-829-9025 or ProductAvailability@icumed.com
4                                         800-631-2174
5                                         800-828-9393
6                                         609-987-5800
7                                         866-634-9120
8                                         800-796-9526
9                                         844-646-4398
10                                        888-238-7880
11                                        844-646-4398
12                                        800-672-6372
13                                        844-646-4398
14                                        800-706-5575
15                                        800-533-4535
16                                        866-625-1918
17                                        833-493-4689
18                                        800-796-9526
19    1-866-829-9025 or ProductAvailability@icumed.com
Name: contact_info, dtype: object

In [36]:
# Extract contact_info into a separate table keyed by package_ndc

shortage_contacts = (
    shortage_df[["package_ndc", "contact_info"]]
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
)

shortage_contacts.head()

    package_ndc                                      contact_info
0  0781-2868-10                                      800-525-8747
1  72888-153-05                           sales@advagenpharma.com
2  0003-3641-11                                      800-332-2056
3  0990-6139-03  1-866-829-9025 or ProductAvailability@icumed.com
4  17478-050-05                                      800-631-2174

In [37]:
# Remove contact_info from the core shortages table after normalization

drug_shortages = drug_shortages.drop(columns=["contact_info"], errors="ignore")

drug_shortages.head()

,package_ndc,generic_name,company_name,status,availability,shortage_reason,update_type,initial_posting_date,update_date,discontinued_date,change_date,resolved_note,therapeutic_category,dosage_form,presentation
0,0781-2868-10,Omeprazole Delayed Release Capsule,Sandoz Inc.,To Be Discontinued,NaN,NaN,New,2025-10-09,2025-10-09,2025-10-09,NaN,NaN,[Gastroenterology],NaN,"Omeprazole, Delayed Release Capsule, 20 mg (ND..."
1,72888-153-05,Clonazepam Tablet,Rubicon Research Private Limited,Current,Available,NaN,Reverified,2023-03-10,2026-01-05,<NA>,NaN,NaN,"[Neurology, Pediatric, Psychiatry]",Tablet,"Clonazepam, Tablet, 1 mg (NDC 72888-153-05)"
2,0003-3641-11,Atazanavir Sulfate; Cobicistat Tablet,Bristol Myers Squibb Co.,To Be Discontinued,NaN,NaN,New,2025-11-03,2025-11-03,2025-11-03,NaN,NaN,[Antiviral],Tablet,"Evotaz, Tablet, 300 mg; 150 mg (NDC 0003-3641-11)"
3,0990-6139-03,Sterile Water Irrigant,Otsuka ICU Medical LLC,Current,Limited Availability,Other,Reverified,2023-04-28,2026-01-23,<NA>,NaN,NaN,"[Gastroenterology, Other, Pediatric]",Irrigant,"Sterile Water In Plastic Container, Irrigant, ..."
4,17478-050-05,Sufentanil Citrate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,Unavailable,Other,Revised,2022-05-03,2026-01-22,<NA>,NaN,NaN,"[Analgesia/Addiction, Pediatric]",Injection,"Sufentanil Citrate, Injection, 50 mcg/1 mL (ND..."

In [38]:
# Join drug shortages to NDC packaging on package_ndc

shortages_with_ndc = drug_shortages.merge(
    ndc_packaging,
    on="package_ndc",
    how="left"
)

shortages_with_ndc.head()

,package_ndc,generic_name,company_name,status,availability,shortage_reason,update_type,initial_posting_date,update_date,discontinued_date,change_date,resolved_note,therapeutic_category,dosage_form,presentation,product_ndc,description,marketing_start_date,marketing_end_date,sample
0,0781-2868-10,Omeprazole Delayed Release Capsule,Sandoz Inc.,To Be Discontinued,NaN,NaN,New,2025-10-09,2025-10-09,2025-10-09,NaN,NaN,[Gastroenterology],NaN,"Omeprazole, Delayed Release Capsule, 20 mg (ND...",0781-2868,"1000 CAPSULE, DELAYED RELEASE in 1 BOTTLE (078...",2019-07-01,<NA>,False
1,72888-153-05,Clonazepam Tablet,Rubicon Research Private Limited,Current,Available,NaN,Reverified,2023-03-10,2026-01-05,<NA>,NaN,NaN,"[Neurology, Pediatric, Psychiatry]",Tablet,"Clonazepam, Tablet, 1 mg (NDC 72888-153-05)",72888-153,500 TABLET in 1 BOTTLE (72888-153-05),2022-10-10,<NA>,False
2,0003-3641-11,Atazanavir Sulfate; Cobicistat Tablet,Bristol Myers Squibb Co.,To Be Discontinued,NaN,NaN,New,2025-11-03,2025-11-03,2025-11-03,NaN,NaN,[Antiviral],Tablet,"Evotaz, Tablet, 300 mg; 150 mg (NDC 0003-3641-11)",0003-3641,30 TABLET in 1 BOTTLE (0003-3641-11),2015-01-29,<NA>,False
3,0990-6139-03,Sterile Water Irrigant,Otsuka ICU Medical LLC,Current,Limited Availability,Other,Reverified,2023-04-28,2026-01-23,<NA>,NaN,NaN,"[Gastroenterology, Other, Pediatric]",Irrigant,"Sterile Water In Plastic Container, Irrigant, ...",0990-6139,"24 BOTTLE, PLASTIC in 1 CASE (0990-6139-03) /...",2019-09-01,2026-05-01,False
4,17478-050-05,Sufentanil Citrate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,Unavailable,Other,Revised,2022-05-03,2026-01-22,<NA>,NaN,NaN,"[Analgesia/Addiction, Pediatric]",Injection,"Sufentanil Citrate, Injection, 50 mcg/1 mL (ND...",NaN,NaN,<NA>,<NA>,NaN

In [39]:
# Check how many shortage records successfully joined to NDC packaging

shortages_with_ndc["product_ndc"].isna().value_counts()

product_ndc
False    1647
True      191
Name: count, dtype: int64

In [40]:
# Inspect shortages that did not match NDC packaging

unmatched_shortages = shortages_with_ndc[shortages_with_ndc["product_ndc"].isna()]
unmatched_shortages[["package_ndc", "generic_name", "company_name"]].head()

,package_ndc,generic_name,company_name
4,17478-050-05,Sufentanil Citrate Injection,"Hikma Pharmaceuticals USA, Inc."
21,55566-2500-0,Desmopressin Acetate Spray,Ferring
22,0378-0167-02,Doxycycline Hyclate Tablet,"Mylan Pharmaceuticals Inc., a Viatris Company"
25,0409-4902-34,Dextrose Monohydrate 50% Injection,"Hospira, Inc., a Pfizer Company"
30,43598-441-01,"Methylphenidate Hydrochloride Tablet, Extended...","Dr. Reddy's Laboratories, Inc."

In [41]:
# Confirm final analysis table shape after join

shortages_with_ndc.shape

(1838, 20)

In [42]:
# Save final analysis-ready tables

shortages_with_ndc.to_csv("data/shortages_with_ndc.csv", index=False)
drug_shortages.to_csv("data/drug_shortages_core.csv", index=False)
shortage_contacts.to_csv("data/shortage_contacts.csv", index=False)

# Begin analysis of FDA drug shortages using the final joined shortages + NDC dataset.

In [43]:
# Count shortages by status

shortages_with_ndc["status"].value_counts()

status
Current               1177
To Be Discontinued     527
Resolved               134
Name: count, dtype: int64

In [44]:
# Count shortages by therapeutic category

shortages_with_ndc["therapeutic_category"].value_counts().head(10)

therapeutic_category
[Psychiatry]                            254
[Anesthesia]                            231
[Cardiovascular]                        192
[Analgesia/Addiction]                   132
[Endocrinology/Metabolism]               95
[Anti-Infective]                         76
[Gastroenterology, Other, Pediatric]     70
[Anesthesia, Pediatric]                  70
[Oncology]                               65
[Neurology]                              64
Name: count, dtype: int64

In [45]:
# Count shortages by dosage form

shortages_with_ndc["dosage_form"].value_counts().head(10)

dosage_form
Injection                    1082
Tablet                        444
Capsule                       158
Capsule, Extended Release      21
Tablet, Chewable               19
Solution                       14
Powder                         10
Cream                          10
Irrigant                        9
Powder, For Solution            8
Name: count, dtype: int64

In [46]:
# Count shortages by manufacturer

shortages_with_ndc["company_name"].value_counts().head(10)

company_name
Hospira, Inc., a Pfizer Company    214
Fresenius Kabi USA, LLC            174
Teva Pharmaceuticals USA, Inc.     127
Hikma Pharmaceuticals USA, Inc.     97
Baxter Healthcare                   90
Pfizer Inc.                         81
Upsher-Smith Laboratories, LLC      73
Sandoz Inc.                         48
Eugia US LLC                        48
Aurobindo Pharma USA                40
Name: count, dtype: int64

In [47]:
# Status distribution for top manufacturers

top_manufacturers = shortages_with_ndc["company_name"].value_counts().head(10).index

shortages_with_ndc[
    shortages_with_ndc["company_name"].isin(top_manufacturers)
].groupby(["company_name", "status"]).size().unstack(fill_value=0)

status                           Current  Resolved  To Be Discontinued
company_name
Aurobindo Pharma USA                  19         0                  21
Baxter Healthcare                     62        27                   1
Eugia US LLC                          48         0                   0
Fresenius Kabi USA, LLC              156        11                   7
Hikma Pharmaceuticals USA, Inc.       92         4                   1
Hospira, Inc., a Pfizer Company      168        10                  36
Pfizer Inc.                           37        12                  32
Sandoz Inc.                           11         2                  35
Teva Pharmaceuticals USA, Inc.        44         1                  82
Upsher-Smith Laboratories, LLC         0         0                  73

In [49]:
# Calculate shortage duration using initial_posting_date and latest update_date

shortages_with_ndc["initial_posting_date"] = pd.to_datetime(
    shortages_with_ndc["initial_posting_date"], errors="coerce"
)

shortages_with_ndc["update_date"] = pd.to_datetime(
    shortages_with_ndc["update_date"], errors="coerce"
)

shortages_with_ndc["duration_days"] = (
    shortages_with_ndc["update_date"] - shortages_with_ndc["initial_posting_date"]
).dt.days

shortages_with_ndc["duration_days"].describe()

count    1838.000000
mean     1349.380849
std      1295.366206
min         0.000000
25%         0.000000
50%      1037.000000
75%      2110.000000
max      5136.000000
Name: duration_days, dtype: float64

# Relational analysis begins here: insights derived from the joined drug shortages + NDC packaging dataset

In [50]:
# Analyze package-level shortages with identifying drug, manufacturer, and packaging details

# Create a package-level shortage view with key identifying fields

package_shortage_view = shortages_with_ndc[
    [
        "generic_name",
        "company_name",
        "status",
        "description",
        "product_ndc",
        "package_ndc"
    ]
].drop_duplicates()

package_shortage_view.head(10)

,generic_name,company_name,status,description,product_ndc,package_ndc
0,Omeprazole Delayed Release Capsule,Sandoz Inc.,To Be Discontinued,"1000 CAPSULE, DELAYED RELEASE in 1 BOTTLE (078...",0781-2868,0781-2868-10
1,Clonazepam Tablet,Rubicon Research Private Limited,Current,500 TABLET in 1 BOTTLE (72888-153-05),72888-153,72888-153-05
2,Atazanavir Sulfate; Cobicistat Tablet,Bristol Myers Squibb Co.,To Be Discontinued,30 TABLET in 1 BOTTLE (0003-3641-11),0003-3641,0003-3641-11
3,Sterile Water Irrigant,Otsuka ICU Medical LLC,Current,"24 BOTTLE, PLASTIC in 1 CASE (0990-6139-03) /...",0990-6139,0990-6139-03
4,Sufentanil Citrate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,NaN,NaN,17478-050-05
5,Acetaminophen; Oxycodone Hydrochloride Tablet,"Endo Pharmaceuticals, Inc.",To Be Discontinued,100 TABLET in 1 BOTTLE (60951-712-70),60951-712,60951-712-70
6,Somatropin Injection,"Novo Nordisk, Inc.",Resolved,1 SYRINGE in 1 CARTON (0169-7703-21) / 3 mL i...,0169-7703,0169-7703-21
7,Bacitracin Ophthalmic Ointment,Padagis US LLC,Current,1 TUBE in 1 CARTON (0574-4022-35) / 3.5 g in ...,0574-4022,0574-4022-35
8,Lisdexamfetamine Dimesylate Capsule,"Mylan Pharmaceuticals Inc., a Viatris Company",Current,"90 CAPSULE in 1 BOTTLE, PLASTIC (0378-6859-77)",0378-6859,0378-6859-77
9,Rocuronium Bromide Injection,"Hospira, Inc., a Pfizer Company",Current,"10 VIAL, MULTI-DOSE in 1 CARTON (0409-5160-10)...",0409-5160,0409-5160-10

In [35]:
# Focus on current shortages at the package level

current_package_shortages = package_shortage_view[
    package_shortage_view["status"] == "Current"
]

current_package_shortages.head(10)

,generic_name,company_name,status,description,product_ndc,package_ndc
0,Morphine Sulfate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,10 AMPULE in 1 CARTON (0641-6019-10) / 10 mL ...,0641-6019,0641-6019-10
2,Lisdexamfetamine Dimesylate Capsule,Apotex Corp.,Current,100 CAPSULE in 1 BOTTLE (60505-4745-1),60505-4745,60505-4745-1
3,Naltrexone Hydrochloride Tablet,"Sun Pharmaceutical Industries, Inc.",Current,"30 TABLET, FILM COATED in 1 BOTTLE (47335-326-83)",47335-326,47335-326-83
4,Dobutamine Hydrochloride Injection,"Hainan Poly Pharm. Co., Ltd.",Current,"1 VIAL, SINGLE-DOSE in 1 CARTON (70436-203-80)...",70436-203,70436-203-80
5,Dobutamine Hydrochloride Injection,Baxter Healthcare,Current,18 BAG in 1 CARTON (0338-1075-02) / 250 mL in...,0338-1075,0338-1075-02
6,"Epinephrine Bitartrate, Lidocaine Hydrochlorid...","Fresenius Kabi USA, LLC",Current,"25 VIAL, MULTI-DOSE in 1 TRAY (63323-483-57) ...",63323-483,63323-483-57
7,"Epinephrine Bitartrate, Lidocaine Hydrochlorid...","Fresenius Kabi USA, LLC",Current,"25 VIAL, SINGLE-DOSE in 1 TRAY (63323-489-17) ...",63323-489,63323-489-17
8,Methylprednisolone Acetate Injection,Pfizer Inc.,Current,"1 VIAL, SINGLE-DOSE in 1 PACKAGE (0009-3073-22...",0009-3073,0009-3073-22
11,"Amphetamine Aspartate Monohydrate, Amphetamine...",Sandoz Inc.,Current,100 TABLET in 1 BOTTLE (0185-0842-01),0185-0842,0185-0842-01
12,Bumetanide Injection,MSN Laboratories Private Limited,Current,NaN,NaN,72205-101-01

In [51]:
# Identify products with shortages affecting multiple package configurations

# Count number of affected packages per product

product_package_counts = (
    shortages_with_ndc
    .groupby(["product_ndc", "generic_name"])
    .agg(
        affected_packages=("package_ndc", "nunique"),
        manufacturer=("company_name", "first")
    )
    .reset_index()
)

# Focus on products with more than one affected package
multi_package_shortages = product_package_counts[
    product_package_counts["affected_packages"] > 1
].sort_values("affected_packages", ascending=False)

multi_package_shortages.head(10)

,product_ndc,generic_name,affected_packages,manufacturer
188,0338-0049,Sodium Chloride 0.9% Injection,10,Baxter Healthcare
186,0338-0017,Dextrose Monohydrate 5% Injection,9,Baxter Healthcare
944,63323-285,Ropivacaine Hydrochloride Injection,8,"Fresenius Kabi USA, LLC"
945,63323-286,Ropivacaine Hydrochloride Injection,6,"Fresenius Kabi USA, LLC"
362,0409-6102,Furosemide Injection,6,"Hospira, Inc., a Pfizer Company"
584,0990-7922,Dextrose Monohydrate 5% Injection,5,Otsuka ICU Medical LLC
590,0990-7984,Sodium Chloride 0.9% Injection,5,Otsuka ICU Medical LLC
994,63323-806,Fentanyl Citrate Injection,5,"Fresenius Kabi USA, LLC"
585,0990-7923,Dextrose Monohydrate 5% Injection,5,Otsuka ICU Medical LLC
589,0990-7983,Sodium Chloride 0.9% Injection,5,Otsuka ICU Medical LLC

In [52]:
# Assess manufacturer exposure based on the number of affected package configurations

# Count distinct affected packages per manufacturer

manufacturer_package_exposure = (
    shortages_with_ndc
    .groupby("company_name")
    .agg(
        affected_packages=("package_ndc", "nunique"),
        affected_products=("product_ndc", "nunique")
    )
    .reset_index()
    .sort_values("affected_packages", ascending=False)
)

manufacturer_package_exposure.head(10)

                        company_name  affected_packages  affected_products
59   Hospira, Inc., a Pfizer Company                201                122
45           Fresenius Kabi USA, LLC                174                103
128   Teva Pharmaceuticals USA, Inc.                124                 89
58   Hikma Pharmaceuticals USA, Inc.                 97                 90
22                 Baxter Healthcare                 87                 46
102                      Pfizer Inc.                 81                 60
132   Upsher-Smith Laboratories, LLC                 73                 39
113                      Sandoz Inc.                 48                 34
41                      Eugia US LLC                 48                 48
16              Aurobindo Pharma USA                 39                 27

In [53]:
# Identify manufacturers with the highest number of currently active package-level shortages

# Focus on current shortages only
current_shortages = shortages_with_ndc[
    shortages_with_ndc["status"] == "Current"
]

# Count active affected packages per manufacturer
current_manufacturer_risk = (
    current_shortages
    .groupby("company_name")
    .agg(
        current_affected_packages=("package_ndc", "nunique"),
        current_affected_products=("product_ndc", "nunique")
    )
    .reset_index()
    .sort_values("current_affected_packages", ascending=False)
)

current_manufacturer_risk.head(10)

,company_name,current_affected_packages,current_affected_products
38,"Hospira, Inc., a Pfizer Company",168,102
31,"Fresenius Kabi USA, LLC",156,91
37,"Hikma Pharmaceuticals USA, Inc.",92,86
14,Baxter Healthcare,62,36
27,Eugia US LLC,48,48
88,"Teva Pharmaceuticals USA, Inc.",44,40
68,Pfizer Inc.,37,28
0,Accord Healthcare Inc.,26,14
64,Otsuka ICU Medical LLC,24,12
32,Gland Pharma Limited,24,13